<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AssemblyName>WindowsKVM.Protocol</AssemblyName>
    <RootNamespace>WindowsKVM.Protocol</RootNamespace>
  </PropertyGroup>
</Project>
