<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0-windows10.0.19041.0</TargetFramework>
    <SupportedOSPlatformVersion>10.0.19041.0</SupportedOSPlatformVersion>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AssemblyName>WindowsKVM</AssemblyName>
    <RootNamespace>WindowsKVM</RootNamespace>
    <Version>1.02.10</Version>
    <AssemblyVersion>1.02.10.0</AssemblyVersion>
    <FileVersion>1.02.10.0</FileVersion>
    <RuntimeIdentifiers>win-x64;win-arm64</RuntimeIdentifiers>
    <Platforms>x64;ARM64</Platforms>
    <PublishTrimmed>false</PublishTrimmed>
    <PublishSingleFile>true</PublishSingleFile>
    <ApplicationManifest>app.manifest</ApplicationManifest>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\WindowsKVM.Protocol\WindowsKVM.Protocol.csproj" />
  </ItemGroup>
</Project>
